import 'package:assets_inventory_app_ghum/features/home/models/office.dart';

List<DummyOffice> iOffices = [
  DummyOffice(name: "Aba Lodge", rooms: [
    "Back room (down)",
    "Back room (upstairs)",
    "Dining Area (Downstairs)",
    "Entrance Porch",
    "Governor's Office",
    "Inside the premises",
    "Kitchen (Downstairs)",
    "Kitchen (General)",
    "Kitchen Dining",
    "Kitchen Office",
    "Lobby",
    "Master's Bedroom Upstairs",
    "Parlour Downstairs",
    "Passage",
    "Security Unit",
    "Sitting room extension (downstairs)",
    "Store",
  ]),
  DummyOffice(name: "Admin Annex", rooms: [
    "Admin Office Annex W.O.G",
    "Admin Office W.O.G",
    "Conference Hall W.O.G",
    "D.O.P. Office WOG",
    "Deputy Gov's. Wife Waiting Room",
    "Press Office WOG",
  ]),
  DummyOffice(name: "Admin Pool", rooms: [
    "Admin Downstairs Waiting Room",
    "Admin Office Downstairs",
    "C.A.O Office",
  ]),
  DummyOffice(name: "APSLUP", rooms: [
    "APSLUP (School Feeding Office) WOG",
  ]),
  DummyOffice(name: "Area 4", rooms: [
    "Drivers Office 3",
    "Drivers Office",
    "Fire Service",
    "Transport Unit T.O's Office"
  ]),
  DummyOffice(name: "Banquet Hall", rooms: [
    "Banquet Hall",
  ]),
  DummyOffice(name: "Block B", rooms: [
    "C.P.S",
    "Chief Press Secretary",
    "Conference Room",
    "Legal Office",
    "S.A Monitoring",
    "S.A Political"
  ]),
  DummyOffice(name: "Block C", rooms: [
    "Conference Hall",
    "Diaspora Office Reception",
    "General Office",
    "Office II",
    "Parlour",
    "Rest Room",
    "S.A on Media & Publicity",
    "S.A on Media Waiting Room",
    "Tele Health Premises",
    "Tele Health Hall"
  ]),
  DummyOffice(name: "Block D", rooms: [
    "Due Process",
    "S.A on Health",
  ]),
  DummyOffice(name: "Chief of Staff", rooms: [
    "Chief of Staff Office",
    "Clerical Office",
    "Conference Hall",
    "PA to the COS",
    "Secretary Office COS",
    "Waiting Room",
  ]),
  DummyOffice(name: "Clinic", rooms: [
    "Chief Physician Office",
    "Doctors Consulting Room",
    "Matron Office",
    "Nurses Station",
    "Patient Waiting Room",
  ]),
  DummyOffice(name: "Computer Room", rooms: [
    "Computer Training Centre",
  ]),
  DummyOffice(name: "D.A", rooms: [
    "D.A Office",
  ]),
  DummyOffice(name: "D.F", rooms: [
    "Account Department",
    "Account Unit Deputy D.F",
    "H.O.D Store",
    "Other Charges (2)",
    "Other Charges & Internal Auditor",
    "Pay Roll Account Department",
    "Planning Department",
    "Store",
    "Waiting Room",
  ]),
  DummyOffice(name: "Emeka Omerua Guest House", rooms: [
    "Dinning",
    "Downstairs Passage",
    "Kitchen",
    "Lobby",
    "Parlour",
    "Room 103",
    "Room 104",
    "Room 105",
    "Room 106",
    "Room 107",
    "Room 108",
    "Room 109",
    "Room 110",
    "Room 111",
    "Room 112",
    "Room 113",
    "Room 114",
    "Room 115",
    "Room 116",
    "Room 201",
    "Room 202",
    "Room 203",
    "Room 204",
    "Room 205",
    "Room 206",
    "Room 207",
    "Room 208",
    "Room 209",
    "Upstairs Passage"
  ]),
  DummyOffice(name: "EXCO Chambers", rooms: [
    "EXCO Chambers",
    "Staff Room",
  ]),
  DummyOffice(
      name: "Former S.A on Health Matters",
      rooms: ["Former S.A on Health Matters"]),
  DummyOffice(
    name: "General Kitchen",
    rooms: ["General Kitchen"],
  ),
  DummyOffice(name: "Governor Lodge", rooms: [
    "Blue Room",
    "Dining",
    "DSS Check Point",
    "Premises",
    "Receptionist office",
    "Sitting Room",
    "Visitor's Room"
  ]),
  DummyOffice(name: "Governor's Office", rooms: [
    "Bongo Office",
    "Control Room",
    "Driver Office",
    "DSS Office",
    "Governor's Aides (1)",
    "Governor's Aides (2)",
    "Governor's Office",
    "Office Premises",
    "P.A to the Governor",
    "Security Check Office",
    "Waiting Room",
  ]),
  DummyOffice(name: "Gym House", rooms: [
    "Gym",
  ]),
  DummyOffice(name: "New Presidential Lodge", rooms: [
    "Dinning Down Stairs",
    "Down Stair Room",
    "Kitchen Down Stair",
    "Master Parlour Upstairs",
    "Master Room (1) Upstairs",
    "Parlour Down Stairs",
    "Second Parlour Down Stairs",
    "Step case",
    "Upstairs Dinning",
    "Upstairs Room 2",
    "Upstairs Room 3",
    "Upstairs Room 4",
  ]),
  DummyOffice(
    name: "NIN Office",
    rooms: ["NIN Office"],
  ),
  DummyOffice(
    name: "Operation Crush",
    rooms: ["Operation Crush"],
  ),
  DummyOffice(name: "P.A Office", rooms: [
    "General Office (P.A) (2)",
    "P.A.'s Office (1)",
    "P.A.'s Office (3)",
  ]),
  DummyOffice(name: "Permanent Secretary", rooms: [
    "Open Registry",
    "Permanent Secretary's Office",
    "Secret Registry",
  ]),
  DummyOffice(
    name: "Plant House",
    rooms: ["Plant House"],
  ),
  DummyOffice(
    name: "Policy Implementation",
    rooms: ["Policy Implementation"],
  ),
  DummyOffice(name: "Political Block", rooms: [
    "Political Unit Room 6",
    "Political Unit Room 7",
    "Political Unit Room 9",
    "Political Unit Room 11 Reception",
    "Political Unit Room 19",
    "Political Unit Room 20",
    "Political Unit Room 21",
    "Political Unit Room 22",
    "Political Unit Room 30",
    "Political Unit Room 31",
  ]),
  DummyOffice(
    name: "Porter Unit",
    rooms: ["Porter Unit"],
  ),
  DummyOffice(
      name: "Press Unit",
      rooms: ["Press Unit Director in Charge", "Press Unit"]),
  DummyOffice(
    name: "S.A on IGR",
    rooms: ["S.A on IGR"],
  ),
  DummyOffice(
    name: "S.A on Rural Orientation",
    rooms: ["S.A. (Rural Orientation)"],
  ),
  DummyOffice(
    name: "S.A on Vulnerable",
    rooms: ["S.A on Vulnerable"],
  ),
  DummyOffice(
      name: "S.A Trade Commerce Industry",
      rooms: ["S.A Trade Commerce Industry"]),
  DummyOffice(
    name: "Special Adviser",
    rooms: ["Special Adviser (Admin.)"],
  ),
  DummyOffice(
    name: "Studio",
    rooms: ["Studio"],
  ),
  DummyOffice(
    name: "Unit Commander",
    rooms: ["Police"],
  ),
  DummyOffice(name: "Unity Chapel", rooms: [
    "Premises",
    "Unity Chapel",
  ]),
  DummyOffice(name: "Wife of Governor's", rooms: [
    "Acct",
    "C.P.S Office WOG",
    "Conference Room",
    "Data Processing Office WOG",
    "Driver Unit WOG",
    "Escort Commander Office WOG",
    "G.B.V Room I",
    "G.B.V Room II",
    "Lobby",
    "Main Office",
    "Office I (S.A Special Duties)",
    "Office II (S.A Women Affairs)",
    "Office III (Women Mobilization)",
    "Police",
    "Security Office WOG",
    "Waiting Room",
  ]),
  DummyOffice(name: "Works", rooms: [
    "Electrical Section",
    "Plumbing Section",
    "Water Section",
  ])
];



List<DummyOffice> iOffices2 = [
  DummyOffice(name: "Aba Lodge", rooms: [
    "Back room (upstairs)",
    "Back room (down)",
    "Dining Area (Downstairs)"
  ]),
  DummyOffice(
    name: "Office of Special Duties",
    rooms: [
      "Staff Room",
      "Main Office",
    ],
  ),
  DummyOffice(name: "Clinic", rooms: [
    "Chief Physician Office",
    "Chief Medical Officer Office",
    "Doctors Consulting Room",
    "Chief Matron Office",
    "Nurses Unit",
    "Clerical Staff Office",
  ]),
  DummyOffice(name: "Computer Office", rooms: [
    "Computer room",
    "Media Room",
  ]),
  DummyOffice(name: "Office of the SA on Health", rooms: [
    "Reception",
    "Main Office",
    "Conference Room",
    "Admin Office",
  ]),
  DummyOffice(
      name: "Office of the Special Advicer on Trade Commerce and Industry",
      rooms: [
        "Reception",
        "SA Main Office",
        "Secetariat",
      ]),
  DummyOffice(name: "Information Department", rooms: [
    "Photo Unit",
    "Public enlightment unit (Room 2)",
    "Press Center",
    "Director of Information Office",
  ]),
  DummyOffice(name: "Planning, Research and Statistics Office", rooms: [
    "Main office (DPRS office)",
    "Staff room",
  ]),
  DummyOffice(name: "Office of the Permanent Sectary", rooms: [
    "Main office",
    "Protocol/reception",
    "Confidential secretary office",
    "Administrative department",
    "Inner Office of the Director of Admin.",
    "Admin. Annex",
    "Admin. Extension",
    "Open Registry",
    "Secret Registry",
  ]),
  DummyOffice(name: "Transport Unit", rooms: [
    "Office of the Transport Officer",
    "Area 4",
  ]),
  DummyOffice(name: "Works Department", rooms: [
    "Director of Works Office",
    "Refrigeration and Air Conditioning Unit",
    "Water Supply and Distribution",
    "Building Section",
    "Electrical Section",
  ]),
  DummyOffice(name: "Office of the SA on Security", rooms: [
    "Reception",
    "Store/Commerce",
    "Admin Section",
    "SA's Office",
    "Operation Crush Heaquarters",
    "Reception/Conference Room",
    "Operation OFFR's Office",
    "Civil Servant Room",
    "Head of Operations of the SA on Security",
    "Head of Strategy and Intelligence",
    "Monitoring Room",
    "Radio Room",
  ]),
  DummyOffice(
      name:
          "Office of the SA on Monitoring and Evaluation / SA on Political Matters",
      rooms: [
        "Reception/Conference Room",
        "Office of the SA (Main Office)",
        "PA/Other Workers",
        "Conference Room fo SA on Monitoring/Evaluation",
        "Main Office for SA on Policies Matters",
        "Waiting Room for the SA(s)",
        "Staff Room",
        "Ombudsman/Staff Room",
      ]),
  DummyOffice(
      name: "Office of the Chief Press Secetary to the Governor",
      rooms: [
        "Reception",
        "Studio",
        "HIS Main Office",
        "Conference Room",
      ]),
  DummyOffice(name: "Office of the COS", rooms: [
    "PA's Office",
    "Waiting Room",
    "SA on Technical",
    "Secetariat Annex",
    "Conference Room",
  ]),
  DummyOffice(name: "Office of the DCOS/SA on Sports/Youths", rooms: [
    "Reception",
    "Secetariat",
    "Conference Room",
    "DCOS Main Office",
  ]),
  DummyOffice(name: "Due Process Office", rooms: [
    "Reception",
    "Secetariat",
    "Conference Room",
    "Head/SSA",
    "DF's Office",
    "DD infor/HOD PRS/Info Office",
    "Quantity ?? Procurement Office",
  ]),
  DummyOffice(name: "Office of SA on Media", rooms: [
    "SA's Main Office",
    "Reception",
    "PA to the SA",
  ]),
  DummyOffice(name: "Office of the SSG", rooms: [
    "DA/Infor/PRO",
    "Registry",
    "Secetariat",
    "Reception",
    "SGG's Main Office",
  ]),
  DummyOffice(name: "Commissioner for Health Office", rooms: [
    "Conference Room",
    "Commisioner's Office",
    "Strategy/Staff Room",
  ]),
  DummyOffice(name: "NIN's Office", rooms: [
    'Main Room',
  ]),
  DummyOffice(name: "Accounts Department", rooms: [
    "Secetariat",
    "DF's Office",
    "Other Charges I",
    "Other Charges II",
    "Cashier",
    "DD's Office",
    "Payroll",
    "Auditor's Office",
  ]),
  DummyOffice(name: "Store Unit", rooms: [
    "Room 1",
    "Room 2",
  ])
];
